name: 'Setup env'
description: 'Action to setup environment variables'
author: SebasRusuu

inputs:
  GIT_USER:
    description: 'Git user'
    required: true
  GIT_PASS:
    description: 'Git password'
    required: true
  GIT_HUB_TOKEN:
    description: 'GitHub token'
    required: true

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: yarn
        cache-dependency-path: site/package-lock.json
    - name: Install Dependencies
      shell: bash
      run: yarn install
      working-directory: site

    - name: Set Environment Variables
      shell: bash
      run: |
        echo "Setting up environment variables"
        echo "GIT_USER=${{ inputs.GIT_USER }}" >> $GITHUB_ENV
        echo "GIT_PASS=${{ inputs.GIT_PASS }}" >> $GITHUB_ENV
        echo "GIT_HUB_TOKEN=${{ inputs.GIT_HUB_TOKEN }}" >> $GITHUB_ENV