env:
  GIT_USER: ${{ secrets.GIT_USER }}
  GIT_PASS: ${{ secrets.GIT_HUB_TOKEN }}
platforms:
  - os: Windows
    osVersion: 10
    browserName: Chrome
    browserVersion: 120.0
  - os: OS X
    osVersion: 12
    browserName: Safari
    browserVersion: 15.6
  - deviceName: iPhone 13
    osVersion: 15
    browserName: Chromium
    deviceOrientation: portrait
parallelsPerPlatform: 1
browserstackLocal: true
buildName: Run parallelo
projectName: automation
debug: true
networkLogs: true
consoleLogs: info