name: Run tests and publish report
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Run tests
        run: make test-outstanding

  gen-report:
    if: always()
    name: Generate Allure Report and Send Teams Notification
    runs-on: ubuntu-latest
    needs:
      - test

    steps:
          - uses: actions/checkout@v4
            with:
              ref: gh_page

          - name: Generate Allure Report
            uses: ./.github/actions/allure-report
            with:
              publish_branch: gh-pages
              publish_dir: allure-history