name: Deploy Website
on: [ push ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./site/

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
            node-version: 18
            cache: yarn

      - name: Install dependencies
        run: yarn install

      - name: Test build website
        run: |
          yarn build

#      - name: Deploy Site
#        run: make web
#        env:
#          GIT_USER: ${{ secrets.GIT_USER }}
#          GIT_PASS: ${{ secrets.GIT_PASS }}
#          GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
#          GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
#          CUSTOM_COMMIT_MESSAGE: ${{ secrets.CUSTOM_COMMIT_MESSAGE }}