name: Run web tests
on:
  workflow_dispatch:
    inputs:
      browser_name:
        required: true
        description: 'Browser to run tests against'

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: true
    defaults:
      run:
        working-directory: java-selenium4/outstanding

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Run build
        run: mvn install -DskipTests

      - name: Run tests
        run: |
          echo "Running tests on ${{ input.browser }}"
          mvn test -Dselenium.browser=${{ input.browser }}
        if: always()
      - name: Generate Allure test report
        run: mvn allure:report

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: ${{ input.browser }}
          path: screenshots/

      - uses: actions/upload-artifact@yt
        with:
          name: artifact-allure-report-${{ input.browser }}
          path: java-selenium4/outstanding/target/site/allure-maven-plugin
          if-no-files-found: error
          retention-days: 1
          overwrite: true
          compression-level: 6

