name: Run tests and publish report
on:
  - workflow_call
  - workflow_dispatch

jobs:
  prallel-test:
    strategy:
      fail-fast: false
      matrix:
        browser: [ 'chrome', 'firefox' ]
    uses: ./.github/workflows/github-web-run.yml
    with:
      browser_name: ${{ matrix.browser }}

  site:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: site
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: ./.github/actions/setup

      - name: Build site
        run: yarn build

      - name: Deploy site
        run: yarn deploy
        env:
          GIT_USER: ${{ secrets.GIT_USER }}
          GIT_PASS: ${{ secrets.GIT_HUB_TOKEN }}

  publish-allure-result:
    needs: site
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    environment:
      name: allure_url
      url: https://sebasrusuu.github.io/automation/java-selenium4/outstanding/artifact-allure-report-${{ inputs.browser_name }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up git
        uses: ./.github/actions/setup/git
        with:
          email: 'sebastiaotr.5@gmail.com'
          name: 'SebasRusuu'

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.browser }}
          path: artifact-allure-report-${{ inputs.browser }}

      - uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.browser }}
          path: artifact-allure-report-${{ inputs.browser }}

      - name: Set Allure Report URL
        run: echo "ALLURE_URL=https://sebasrusuu.github.io/automation/java-selenium4/outstanding/artifact-allure-report-${{ inputs.browser_name }}" >> $GITHUB_ENV

      - name: Publish allure report
        run: |
          git add artifact-allure-report
          git commit -m "Publish allure report"
          git push https://${{secrets.GIT_HUB_TOKEN}}@github.com/sebasrusuu/automation.git