name: github-actions

on:
  pull_request:
    branches:
      - 'qa/outstanding-framework-java'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Makefile build
        run: make test-outstanding