name: Run tests and publish report
on:
  - push
  - workflow_call


jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: java-selenium4/outstanding
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Run build
        run: mvn install -DskipTests

      - name: Run test
        run: |
          mvn test
          mvn allure:report

      - uses: actions/upload-artifact@v4
        with:
          name: artifact-allure-report
          path: java-selenium4/outstanding/target/site/allure-maven-plugin
          if-no-files-found: error
          retention-days: 1
          overwrite: true
          compression-level: 6




  site:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: site
    needs: test
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: ./.github/actions/setup

      - name: Build site
        run: yarn build

      - name: Deploy site
        run: yarn deploy
        env:
          GIT_USER: ${{ secrets.GIT_USER }}
          GIT_PASS: ${{ secrets.GIT_HUB_TOKEN }}


  publish-allure-result:
    needs: site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: artifact-allure-report
          uses: ./.github/actions/setup/git
          with:
            email: 'sebastiaotr.5@gmail.com'
            name: 'SebasRusuu'


