name: github-actions

on:
  push:
    branches:
      - 'qa/outstanding-framework-java'
  pull_request:
    branches:
      - 'qa/outstanding-framework-java'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up Allure
        run: |
          sudo apt-add-repository ppa:qameta/allure -y
          sudo apt-get update
          sudo apt-get install allure -y

      - name: Install dependencies
        run: mvn install -DskipTests

      - name: Run tests
        run: mvn clean test

      - name: Generate Allure report
        run: mvn allure:report