name: Run web tests
on:
  workflow_dispatch:
    inputs:
      browser_name:
        required: true
        description: 'Browser to run tests against'
  workflow_call:
    inputs:
      browser_name:
        required: true
        type: string
        description: 'Browser to run tests against'

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: true
    defaults:
      run:
        working-directory: java-selenium4/outstanding

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Run build
        run: mvn install -DskipTests
      - name: Run tests
        run: |
          echo "Running tests on ${{ inputs.browser_name }}"
          mvn test -Dselenium.browser=${{ inputs.browser_name }}

      - name: Generate Allure test report
        if: always()
        run: mvn allure:report

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: artifact-allure-report-${{ inputs.browser_name }}
          path: java-selenium4/outstanding/target/site/allure-maven-plugin
          if-no-files-found: error
          retention-days: 1
          overwrite: true
          compression-level: 6

      - name: git config
        uses: ./.github/actions/setup/git
        with:
          email: 'sebastiaotr.5@gmail.com'
          name: 'SebasRusuu'

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Publish allure report
        run: |
          git add artifact-allure-report-${{ inputs.browser_name }}
          git commit -m "Publish allure report"
          git push https://${{secrets.GIT_HUB_TOKEN}}@github.com/sebasrusuu/automation.git


