name: Run tests and publish report
on:
  - workflow_call
  - workflow_dispatch

jobs:
  parallel-test:
    strategy:
      fail-fast: false
      matrix:
        browser: [ 'chrome', 'firefox' ]
    uses: ./.github/workflows/github-web-run.yml
    with:
      browser_name: ${{ matrix.browser }}
    permissions:
      contents: write
      pull-requests: write

  site:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: site
    needs: parallel-test
    environment:
      name: docs_url
      url: https://sebasrusuu.github.io/automation/
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: ./.github/actions/setup

      - name: Build site
        run: yarn build
      - name: DOCUS URL
        run: echo "DOCUS_URL=https://sebasrusuu.github.io/automation/java-selenium4/outstanding/artifact-allure-report-${{ matrix.browser }}" >> $GITHUB_ENV

      - name: Deploy site
        run: | 
            yarn deploy
            echo "Docs url: ${{ env.DOCUS_URL }}"
        env:
          GIT_USER: ${{ secrets.GIT_USER }}
          GIT_PASS: ${{ secrets.GIT_HUB_TOKEN }}

  publish-allure-result:
    needs: site
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    environment:
      name: allure_url
      url: https://sebasrusuu.github.io/automation/java-selenium4/outstanding/artifact-allure-report-${{ inputs.browser_name }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: gh-pages
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: artifact-allure-report-${{ inputs.browser_name }}
          path: java-selenium4/outstanding/target/site/allure-maven-plugin
          if-no-files-found: error
          retention-days: 1
          overwrite: true
          compression-level: 6

      - name: Set up git
        uses: ./.github/actions/setup/git
        with:
          email: 'sebastiaotr.5@gmail.com'
          name: 'SebasRusuu'

      - uses: actions/download-artifact@v4
        with:
          name: artifact-allure-report-${{ inputs.browser }}
          path: java-selenium4/outstanding/artifact-allure-report-${{ inputs.browser }}

      - name: Set Allure Report URL
        run: echo "ALLURE_URL=https://sebasrusuu.github.io/automation/java-selenium4/outstanding/artifact-allure-report-${{ matrix.browser }}" >> $GITHUB_ENV

      - name: Publish allure report
        run: |
          git add artifact-allure-report-${{ inputs.browser }}
          git commit -m "Publish allure report ${{ inputs.browser }}"
          git push https://${{ secrets.GIT_HUB_TOKEN }}@github.com/sebasrusuu/automation.git
          echo "Allure report url: ${{ env.ALLURE_URL }}"        
