name: Run tests and publish report
on:
  - push
  - workflow_call


jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: java-selenium4/outstanding
    steps:
      - uses: actions/checkout@v3

      - name: test-direcotry
        run: |
          ls -l
          exit 1
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Run build
        run: mvn install -DskipTests

      - name: Run test
        run: |
          cd java-selenium4/outstanding
          mvn test
          mvn allure:report

      - uses: actions/upload-artifact@v4
        with:
          name: artifact-allure-report
          path: java-selenium4/outstanding/target/site/allure-maven-plugin
          if-no-files-found: error
          retention-days: 1
          overwrite: true
          compression-level: 6




  site:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: site
    needs: test
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: yarn install

      - name: Build site
        run: yarn build

      - name: Deploy site
        run: yarn deploy
