name: Deploy Website
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Environment
        uses: ./.github/actions/setup
        with:
          GIT_USER: ${{ secrets.GIT_USER }}
          GIT_PASS: ${{ secrets.GIT_PASS }}
          GIT_HUB_TOKEN: ${{ secrets.GIT_HUB_TOKEN }}

      - name: Deploy Site
        run: make web
        env:
          GIT_USER: ${{ secrets.GIT_USER }}
          GIT_PASS: ${{ secrets.GIT_PASS }}
          GIT_HUB_TOKEN: ${{ secrets.GIT_HUB_TOKEN }}

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4